### ISSUE TITLE
[Feature]: Add example app for testing the subscribe performance

### ISSUE THREAD

**Issue by Chrylo** [eclipse-velocitas/vehicle-app-python-sdk#125]
### Description

For performance measurement purposes an example test app should be provided which subscribes to a number of signals and prints out the signal information + timestamps on the initial response.

### Suggested Solution

- The Test-App subscribes to any 100 signals and waits for the initial response
- The Test-App prints out TIMESTAMP, SIGNAL NAME and SIGNAL VALUE on stdout after the initial response, should be on a single line and parseable.
- Added under the "examples" folder with all the other example apps

**Comment by erikbosch** [comment]
PR merged so closing this one
