### ISSUE TITLE
[Bug]: Native middleware connects to MQTT in constructor

### ISSUE THREAD

**Issue by doosuu** [eclipse-velocitas/vehicle-app-python-sdk#143]
### Severity

Medium

### What release version, tag or commit-hash did you use?

v0.14.1

### Current Behavior

When instantiating the native middleware, it already connects to MQTT.

### Steps to Reproduce

Instantiate native middleware

### Expected Behavior

MQTT connection happens in `Middleware.start()`

### Code of Conduct

- [X] I agree to follow this project's "Code of Conduct".

**Comment by MP91** [comment]
fixed with #146
