### ISSUE TITLE
[Bug]: DevContainer name for VehicleApp Python SDK is same as for VehicleApp Python Template

### ISSUE THREAD

**Issue by DocMoebiuz** [eclipse-velocitas/vehicle-app-python-sdk#24]
### What happened?

DevContainer name for VehicleApp Python SDK is same as for Vehicle App Python Template. When both DevContainers are running in VS Code, you cannot distinguish both easily.

Steps to reproduce:
* Start DevContainer

Expected result:
* Name in bottom left shows a specific name, e.g., "VehicleApp Python SDK"

Actual result:
* Name shows "VehicleApp Python"

### Operating System

macOS (Default)

### What release version or branch did you use?

main

### Code of Conduct

- [X] I agree to follow this project's rules for contributions

**Comment by mml5bg** [comment]
Fixed in the following PR: https://github.com/eclipse-velocitas/vehicle-app-python-sdk/pull/31
