### ISSUE TITLE
[Bug]: Missing accessor for DataPoint .timestamp

### ISSUE THREAD

**Issue by mikehaller** [eclipse-velocitas/vehicle-app-python-sdk#27]
### What happened?

Kuksa Data Broker defines "timestamp" as a metadata for datapoints.
For calculation of for example moving averages, I need to access the timestamps of the data as well.

Unfortunately, the velocitas vehicle model does not seem to expose the ".timestamp" attribute.

### Operating System

Other

### What release version or branch did you use?

main

### Code of Conduct

- [X] I agree to follow this project's rules for contributions

**Comment by doosuu** [comment]
This is a feature we have not been supporting until now. I will pick this up as enhancement and implement it ASAP.

**Comment by dennismeister93** [comment]
Thanks to @doosuu, feature is implemented and merged!
