### ISSUE TITLE
[Bug]: SeatAdjuster App: ModuleNotFoundError: No module named 'vehicle'

### ISSUE THREAD

**Issue by antaradey-itk** [eclipse-velocitas/vehicle-app-python-sdk#79]
### What happened?

SeatAdjuster App in Python SDK does not work anymore. Throws the following error. The application launcher works until v0.8.2.

![seatadjuster_app_error](https://github.com/eclipse-velocitas/vehicle-app-python-sdk/assets/129940848/26c3db2d-8d96-4d6e-b2be-f4403c96a233)

In the current version, import library changed from **sdv_model** to **vehicle** for examples/seatadjuster, and requirement-links.txt does not contain the sdv_model Github [link ](https://github.com/eclipse-velocitas/vehicle-model-python.git)anymore. 

Please explain the issue.

### Operating System

Linux

### What release version or branch did you use?

v0.9.0: latest

### Code of Conduct

- [X] I agree to follow this project's rules for contributions

**Comment by BjoernAtBosch** [comment]
Hi @antaradey-itk ,
fix is provided with #85 and eclipse-velocitas/vehicle-app-python-template#160.
Please have a look, if the solution seems sufficient for you.
I will close this issue for now. Please re-open if further additions are required.
Best regards
