### ISSUE TITLE
Readme for Seat-Adjuster needs update

### ISSUE THREAD

**Issue by mikehaller** [eclipse-velocitas/vehicle-app-python-sdk#82]
### What happened?

The readme in the following repo requires a bit more information on how to run the example:
https://github.com/eclipse-velocitas/vehicle-app-python-sdk/tree/main/examples/seat-adjuster

Esp. it would make sense to describe how to run the application also without DAPR, which environment variables are needed etc. As this is the main example, the readme here should really be updated, as it's the main reference.

Please do not just point to the documentation website.

### Operating System

Other

### What release version or branch did you use?

main

### Code of Conduct

- [X] I agree to follow this project's rules for contributions

**Comment by MP91** [comment]
@mikehaller please check the PR #85 of Björn if this is still valid. If not we could close this issue.

**Comment by mikehaller** [comment]
Yes, thank you for providing information on how to build and configure the example application in the readme.
